[package]
name = "my-game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4", features = ["audio"] }
macroquad-particles = "0.2.2"

[profile.dev.package.'*']
opt-level = 3
